image: node:14

stages:
  - test
  - release

lint:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  tags:
    - docker

test:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  tags:
    - docker

pages:
  stage: release
  before_script:
    - yarn install
  script:
    - yarn build-storybook
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
  tags:
    - docker
